spring.application.name=geocoder

spring.datasource.url=jdbc:postgresql://localhost:5437/${POSTGRES_DB:geocoder}
spring.datasource.username=${POSTGRES_USER:geocoder}
spring.datasource.password=${POSTGRES_PASSWORD:geocoder}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

google.geocoding.api-key=${GOOGLE_API_KEY:}